# Generated by Django 6.1 on 2026-08-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('short_description', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('fa-solid fa-moon', 'Moon'), ('fa-solid fa-heart', 'Heart'), ('fa-solid fa-ring', 'Ring'), ('fa-solid fa-briefcase', 'Briefcase'), ('fa-solid fa-chart-line', 'Chart'), ('fa-solid fa-house', 'House'), ('fa-solid fa-hashtag', 'Hashtag'), ('fa-solid fa-hand', 'Hand / Palmistry'), ('fa-solid fa-fire', 'Fire / Puja'), ('fa-solid fa-clock', 'Muhurat'), ('fa-solid fa-star', 'Horoscope'), ('fa-solid fa-scale-balanced', 'Court Case')], default='fa-solid fa-star', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Consultation fee in INR', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
