# Generated by Django 6.1 on 2026-09-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-is_featured', 'order', 'title']},
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check to display this service prominently in the Featured section on Homepage', verbose_name='Featured Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('fa-solid fa-om', 'Om / Divine'), ('fa-solid fa-star', 'Horoscope / Nakshatra'), ('fa-solid fa-moon', 'Moon / Chandra'), ('fa-solid fa-sun', 'Sun / Surya'), ('fa-solid fa-fire', 'Fire / Havan / Puja'), ('fa-solid fa-ring', 'Ring / Vivah / Marriage'), ('fa-solid fa-heart', 'Heart / Love / Relation'), ('fa-solid fa-gem', 'Gemstone / Ratna'), ('fa-solid fa-house', 'House / Vastu'), ('fa-solid fa-briefcase', 'Briefcase / Career / Job'), ('fa-solid fa-chart-line', 'Chart / Business / Vyapar'), ('fa-solid fa-hand', 'Hand / Palmistry / Hastrekha'), ('fa-solid fa-clock', 'Clock / Shubh Muhurat'), ('fa-solid fa-scale-balanced', 'Scale / Court Case / Dispute'), ('fa-solid fa-feather', 'Feather / Bhagwat Katha'), ('fa-solid fa-shield-halved', 'Shield / Suraksha Kavach'), ('fa-solid fa-bell', 'Temple Bell / Mandir Ghanti')], default='fa-solid fa-star', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
    ]
